# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b686916a19bc3b666f833a4fd463d1d6610fc06451f85a06f0caebaec603b6fd0f7668e3576c062464d02b27e82148d6e96ac4f7a044c60faabb625e091a99

test:
  secret_key_base: d5bed865036804071c02fac8bf5f8ab2a1445af2a4615c486b317e73a605fd22c26b8c295a121aeb90aee7978fd33155a457d60c09bb14964aeb4ff4b27242a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
